### ISSUE TITLE
Default value for study "active" parameter in studies-search

### ISSUE THREAD

**Issue by gcornut** [plantbreeding/brapi-Java-TestServer#1]
Hi,

I'm currently working on a BrAPI harvester that can extract data from multiple BrAPI data sources and I've come across something strange on the BrAPI test server at https://test-server.brapi.org/brapi

The study `"1003"` is accessible at:
GET https://test-server.brapi.org/brapi/v1/studies/1003

But it is not listed in studies-search at:
GET https://test-server.brapi.org/brapi/v1/studies-search

It seems that in the BrAPI test server implementation the `"active"` search parameter is set to `true` by default:
https://github.com/plantbreeding/brapi-Java-TestServer/blob/4d7dba9186b235756a74419b05bca4a1482e572d/src/main/java/org/brapi/test/BrAPITestServer/controller/StudyController.java#L86

Shouldn't it be `null` (using the java `Boolean` type) by default to show both active and inactive studies?

I don't think the [BrAPI study search specification](https://github.com/plantbreeding/API/blob/master/Specification/Studies/StudiesSearch_GET.md) specifies this behaviour.

**Comment by BrapiCoordinatorSelby** [comment]
You are correct, lazy coding on my part. I'll fix this now.
