### ISSUE TITLE
Test Server Calls get_calls pageSize stuck on 2

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#12]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click GET under Calls.

3. Click "Try it out."

4. For dataType, select "application/json."

5. Click Execute.

Even though I did not touch the pageSize text box (leaving it at 1000) the response acts like I specified 2.

**Comment by BrapiCoordinatorSelby** [comment]
I could not re-create this issue. 
Are you looking at the correct output box on Swaggerhub? When you click `Execute`, a new response output box is created to show the actual response from the server. There are always a set of Example responses displayed. The Example response for `GET /calls` shows an example output where `pageSize` is 2, which could be what you are looking at?

I am closing this issue for now, please re-open if you are able to re-create it.
