### ISSUE TITLE
Test Server Calls get_calls dataType Is Ignored

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#15]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click GET under Calls.

3. Click "Try it out."

4. For dataType, select any choice.

5. Click Execute.

No matter what I select for dataType, all 103 calls are returned.

**Comment by BrapiCoordinatorSelby** [comment]
Resolved
e887016

Outstanding Issue: The info returned from /calls does not reflect the reality of the server for the expected data types.

**Comment by BrapiCoordinatorSelby** [comment]
Outstanding issue resolved
ab5d7498cfc579ccf19e8d8ee0cf73fee13447c3
