### ISSUE TITLE
Test Server Studies get_studies metadata Incorrect

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#20]
Fill in 1 for pageSize.  Response header says totalCount 1 (should be 3) and totalPages 1 (should be 3).

Fill in 1 for page and 1 for pageSize.  Response header says totalCount 2 and totalPages 2.

**Comment by BrapiCoordinatorSelby** [comment]
Resolved
c9c3addf939cbff2678f8bc5f34d0dc7bfa790be
