### ISSUE TITLE
Test Server Studies post_search_studies pageSize Ignored

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#21]
When I use pageSize 1, the response says I asked for 1000.

**Comment by BrapiCoordinatorSelby** [comment]
Resolved 
18d85923ae27568e7aaf3766de23b0138f78c936

New Behavior: The `page` and `pageSize` from the POST body are stored with the request. When using GET to retrieve the results of the results of the search, new `page` and `pageSize` parameters may be used. These new values will take precedent over the old values. If no values are provided, the system defaults of 0 and 1000 are used.

Note: It has been suggested that the paging parameters should be removed from the POST body to avoid this sort of confusion. So as a recommendation for future proofing, please do not use the paging parameters in the POST body whenever possible.

> I asked for 1000 and it gave me 2.

This might be related to #12 . Please let me know if you are able to re-create this behavior.
