### ISSUE TITLE
/studies/{studyDbId}/observations Does Not Filter On observationVariableDbIds

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#24]
When I enter "1001" for studyDbId and "MO123:100002" for observationVariableDbIds I am expecting a Response with totalCount == 1 but I get 8.  Am I misunderstanding the method or is there a bug in the server code or is it something else?

**Comment by BrapiCoordinatorSelby** [comment]
@peterrosario you are correct, bug in the server. I am debugging now.

**Comment by BrapiCoordinatorSelby** [comment]
Fixed in e842e953f815a744e62e62f04457049e39ebbc27
Deployed successfully
