### ISSUE TITLE
PUT /studies/{studyDbId}/observations observationTimeStamp

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#25]
First, I put() a value for observationTimeStamp.  Then, I check results by get()ing.  The returned value is from 1970 even though the value I put is in 2013.

**Comment by BrapiCoordinatorSelby** [comment]
fixed in ead9c6788b3d667caf2d094705e9a7f9e8443243
there was a bad conversion from seconds to milliseconds, so it was dumping every date in 1970.
