### ISSUE TITLE
GET /studies/{studyDbId}/table

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#26]
I called this method with studyDbId == 1001.  I tried format == "csv", "tsv", and blank.  All I get back is a file with contents "OrderedMap {}".  Is this correct?

**Comment by BrapiCoordinatorSelby** [comment]
There is an issue, though I'm not sure where you are getting "OrderedMap {}". Check your HTTP status code. When I make the call, I get a 500 error, because there is an NPE in the server. I'm fixing it now.

**Comment by BrapiCoordinatorSelby** [comment]
Fixed in a5eb4777e996c7a74ebc6081d3c4d680c0b05f50

The issue I was seeing has been resolved, I hope this solves your problem as well.

**Comment by peterrosario** [comment]
I just tried it with studyDbId == 1001 and format blank.  I got an error code 406.  There must have been (at least) two problems: the one you solved and a second yet unsolved.  Should I open another issue or will you unclose this one?

**Comment by peterrosario** [comment]
I figured out what was making the test server return error code 406.  The [test server](https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3#/Observations/get_studies__studyDbId__table) has a dropdown box with 3 options: 1) application/csv, 2) application/json, and 3) application/tsv.  Selecting 1) or 3) causes the error.  Selecting 2) does not cause the error.

**Comment by BrapiCoordinatorSelby** [comment]
This is more a problem with the details of the spec and how its presented on SwaggerHub. That drop down on SwaggerHub controls the `Accept` request header. "application/csv" and "application/tsv" are not valid `Accept` headers. If you use something like Postman for testing calls, or directly in your code, you can control the `Accept` header. Use `Accept=application/json` when retrieving JSON content and use `Accept=text/csv` when retrieving CSV content.
