### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#29]
Multiple methods (e.g., GET /calls?page=0?pageSize=1000) produce Code 403 and Error: Response body:

Internal Error. Invalid `proxy-token`. You need to send the SwaggerHub cookie with this request, and populate `proxy-token` with the value inside

**Comment by BrapiCoordinatorSelby** [comment]
Hey @peterrosario sorry to hear you are having trouble. I need more details, what server are you pointed at? what client are you using? 
I just tried hitting https://test-server.brapi.org/brapi/v1/calls?page=0&pageSize=1000 with SwaggerHub UI, Postman, and Firefox, but I could not recreate the issue. 
From the sound of the error, it seems like you are trying to hit a SwaggerHub dummy server. I don't maintain any such servers, so I'm not sure where you found one...

**Comment by peterrosario** [comment]
server: https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3#/
client: Safari

**Comment by peterrosario** [comment]
Just tried it again and now it works.

**Comment by BrapiCoordinatorSelby** [comment]
Cool glad to hear it.
Just so you know, the link you posted is only the URL for the documentation, it is not a valid BrAPI server. When you are using the "Try it out" button on SwaggerHub to test things, after clicking "Execute", notice the 2nd black box labeled "Request URL". That is the url of the server where SwaggerHub is sending requests. For all the BrAPI documentation, that URL will be "https://test-server.brapi.org/brapi/v1/..."
I hope this helps!
