### ISSUE TITLE
Test Server Calls get_calls Fails

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#3]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click GET under Calls.

3. Click "Try it out."

4. For dataType, select "application/json."

5. Click Execute.

Response says error(s) have occurred.

**Comment by BrapiCoordinatorSelby** [comment]
Resolved
e88701602590d4fc0471333fa5975126c2410a8b
