### ISSUE TITLE
PUT /studies/1002/observationunits Produces Error Code 400 Bad Request

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#31]
I ran this on the test server:

curl -X PUT "https://test-server.brapi.org/brapi/v1/studies/1002/observationunits" -H "accept: application/json" -H "Content-Type: application/json" -d "class NewObservationUnitRequests {
    data: [class NewObservationUnitRequest {
        X: null
        Y: null
        blockNumber: 1
        entryNumber: 5
        entryType: TEST
        germplasmDbId: 1
        observationLevel: null
        observationUnitDbId: 5
        observationUnitName: Plot 3
        observationUnitXref: null
        observations: [class Observation {
            germplasmDbId: 1
            germplasmName: Name001
            observationDbId: 9
            observationLevel: null
            observationTimeStamp: 2013-06-14T22:11:51Z
            observationUnitDbId: 5
            observationUnitName: Plot 3
            observationVariableDbId: MO_123:100002
            observationVariableName: Plant height
            operator: null
            season: class Season {
                season: spring
                seasonDbId: 3
                year: 2012
            }
            studyDbId: null
            uploadedBy: null
            value: 2.1
        }]
        plantNumber: 0
        plotNumber: 3
        positionCoordinateX: null
        positionCoordinateXType: null
        positionCoordinateY: null
        positionCoordinateYType: null
        replicate: 0
        studyDbId: null
        treatments: null
    }, class NewObservationUnitRequest {
        X: null
        Y: null
        blockNumber: 1
        entryNumber: 6
        entryType: TEST
        germplasmDbId: 1
        observationLevel: null
        observationUnitDbId: 6
        observationUnitName: Plant 3
        observationUnitXref: null
        observations: [class Observation {
            germplasmDbId: 1
            germplasmName: Name001
            observationDbId: 10
            observationLevel: null
            observationTimeStamp: 2013-06-14T22:12:51Z
            observationUnitDbId: 6
            observationUnitName: Plant 3
            observationVariableDbId: MO_123:100006
            observationVariableName: Virus severity
            operator: null
            season: class Season {
                season: spring
                seasonDbId: 3
                year: 2012
            }
            studyDbId: null
            uploadedBy: null
            value: 4.5
        }]
        plantNumber: 3
        plotNumber: 3
        positionCoordinateX: null
        positionCoordinateXType: null
        positionCoordinateY: null
        positionCoordinateYType: null
        replicate: 0
        studyDbId: null
        treatments: null
    }, class NewObservationUnitRequest {
        X: null
        Y: null
        blockNumber: 1
        entryNumber: 7
        entryType: TEST
        germplasmDbId: 3
        observationLevel: null
        observationUnitDbId: 7
        observationUnitName: Plot 4
        observationUnitXref: null
        observations: [class Observation {
            germplasmDbId: 3
            germplasmName: Name003
            observationDbId: 11
            observationLevel: null
            observationTimeStamp: 2013-06-14T22:13:51Z
            observationUnitDbId: 7
            observationUnitName: Plot 4
            observationVariableDbId: MO_123:100003
            observationVariableName: Carotenoid
            operator: null
            season: class Season {
                season: spring
                seasonDbId: 3
                year: 2012
            }
            studyDbId: null
            uploadedBy: null
            value: 1.4
        }]
        plantNumber: 0
        plotNumber: 4
        positionCoordinateX: null
        positionCoordinateXType: null
        positionCoordinateY: null
        positionCoordinateYType: null
        replicate: 0
        studyDbId: null
        treatments: null
    }, class NewObservationUnitRequest {
        X: null
        Y: null
        blockNumber: 1
        entryNumber: 8
        entryType: CHECK
        germplasmDbId: 3
        observationLevel: null
        observationUnitDbId: 8
        observationUnitName: Plant 4
        observationUnitXref: null
        observations: [class Observation {
            germplasmDbId: 3
            germplasmName: Name003
            observationDbId: 12
            observationLevel: null
            observationTimeStamp: 2013-06-14T22:14:51Z
            observationUnitDbId: 8
            observationUnitName: Plant 4
            observationVariableDbId: MO_123:100005
            observationVariableName: Root color
            operator: null
            season: class Season {
                season: spring
                seasonDbId: 3
                year: 2012
            }
            studyDbId: null
            uploadedBy: null
            value: red
        }]
        plantNumber: 4
        plotNumber: 4
        positionCoordinateX: null
        positionCoordinateXType: null
        positionCoordinateY: null
        positionCoordinateYType: null
        replicate: 0
        studyDbId: null
        treatments: null
    }]
}"

**Comment by BrapiCoordinatorSelby** [comment]
in this case, the error message is correct, this is a bad request.

First Problem: It looks like you have some copy/paste errors at the top of your request JSON. 
This is not valid JSON (looks like a Python object printed maybe?), so the server is rejecting it. 
```
class NewObservationUnitRequests {
data: [class NewObservationUnitRequest {
```

Second Problem: JSON requires double quotes (") around keys and strings AND comma's are required between key/value pairs. 
(`null` is an acceptable keyword and should not have double quotes)
```
"X": null,
"Y": null,
"blockNumber": "1",
"entryNumber": "5",
"entryType": "TEST",
"germplasmDbId": "1",
...
```

Third Problem: The expected Request object is just an array of `ObservationUnits` so the "data:" key is not allowed and will be rejected.

Forth Problem: Once your JSON is cleaned up, your curl statement is missing the "Authorization" header with the admin bearer key required to upload new data to the server.

Whatever language you are using to generate this request, I would suggest you look into using a JSON library for that language to clean up the JSON structure for you. OR better still, find a REST library which manages the JSON and web request for you so you don't need to deal with curl at all. 

Lemme know if you are still running into issues.

**Comment by BrapiCoordinatorSelby** [comment]
Here is a valid curl request that works, for reference. 
```
curl -X PUT "https://test-server.brapi.org/brapi/v1/studies/1002/observationunits" \
 -H "Authorization: Bearer YYYY" -H  "accept: application/json" -H  "Content-Type: application/json" \
-d '[{"blockNumber":"string",
"entryNumber":"string",
"entryType":"string",
"germplasmDbId":"string",
"observationLevel":"string",
"observationUnitDbId":"string",
"observationUnitName":"string",
"observationUnitXref":[{"id":"string","source": "string"}],
"observations":[
{"germplasmDbId":"string",
"germplasmName":"string",
"observationDbId":"string",
"observationLevel":"string",
"observationTimeStamp":"2019-07-08T14:55:39.140Z",
"observationUnitDbId":"string",
"observationUnitName":"string",
"observationVariableDbId":"string",
"observationVariableName":"string",
"operator":"string",
"season":{"season":"string","seasonDbId":"string","year":"string"},
"studyDbId":"string",
"uploadedBy":"string","value":"string"}],
"plantNumber":"string",
"plotNumber":"string",
"positionCoordinateX":"string",
"positionCoordinateXType":"LONGITUDE",
"positionCoordinateY":"string",
"positionCoordinateYType":"LONGITUDE",
"replicate":"string",
"studyDbId":"string",
"treatments": null}]'
```
