### ISSUE TITLE
Test Server Programs get_programs metadata Incorrect

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#4]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click first GET under Programs.

3. Click "Try it out."

4.  For pageSize fill in 3.

5. Click Execute.

Response header says 1) totalCount: 3 (should be 6) and 2) totalPages: 1 (should be 2).

**Comment by BrapiCoordinatorSelby** [comment]
Resolved
e88701602590d4fc0471333fa5975126c2410a8b
