### ISSUE TITLE
GET Crosses does not return parents

### ISSUE THREAD

**Issue by ctucker3** [plantbreeding/brapi-Java-TestServer#48]
Set up: 

POST /observationunits
```
[
	{"observationUnitName": "test"},
	{"observationUnitName": "test2"}
]
```

then POST crosses:
```
[
	{
		"crossName": "200304310\\2003183010",
		"parent1": {
			"observationUnitDbId": "e330b11b-fa77-49a9-922e-992f6da066fc"
		},
		"parent2": {
			"observationUnitDbId": "e330b11b-fa77-49a9-922e-992f6da066fc"
		}
	}
]
```

this will return the parents. But if you GET /crosses, not parents are returned.

**Comment by BrapiCoordinatorSelby** [comment]
@ctucker3 I was unable to reproduce this on `test-server.brapi.org`. I recently made updates to `/POST crosses` (c68b1d6502467966d35dbac35c9119c45cc94e59). Are you sure you have the latest code?

**Comment by ctucker3** [comment]
Ah yep, must be our out of date fork. Nick is updating that now, so it should be working soon. Thanks for checking this out!
