### ISSUE TITLE
POST Observation Units does not save program

### ISSUE THREAD

**Issue by ctucker3** [plantbreeding/brapi-Java-TestServer#49]
Testing the test server: 

POST https://test-server.brapi.org/brapi/v2/observationunits

```
[
	{
              "additionalInfo": {},
              "externalReferences": [
                {
                  "referenceID": "2.0030434E7",
                  "referenceSource": "ou_id"
                }
              ],
              "germplasmDbId": "germplasm1",
              "observationUnitName": "2.0030434E7",
              "programDbId": "program2"
	 }
]
```

Result: 

`programId` comes back null. It is also null in `GET /observationunits`.

**Comment by BrapiCoordinatorSelby** [comment]
So I cheat a little in the database and there is no direct join between OUs and Programs. Totally valid BrAPI request, just an artificial limitation of the test server. Right now you have to provide a studyDbId and it will populate the Trial and Program info from that. I can change this but it will not be a trivial fix. How urgent is this issue?

**Comment by ctucker3** [comment]
This isn't super urgent. I use the test server to do some prelim testing on new features, but am using a local breedbase instance for the real testing. I can just switch to using breedbase for the time being.

**Comment by BrapiCoordinatorSelby** [comment]
I have not tested every combination of crop, program, trial, study, OU that are available. But the original issue adding program to OU has been resolved (and theoretically other combinations have been fixed too)
let me know if you still see similar issues.
