### ISSUE TITLE
Test Server Programs get_programs commonCropName Ignored

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#5]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click first GET under Programs.

3. Click "Try it out."

4. For commonCropName fill in "abc" or "Tomatillo" or leave it blank.

5. Click Execute.

No matter what you do in step 4., the response that is produced is unaffected by the commonCropName value.

**Comment by BrapiCoordinatorSelby** [comment]
Resolved
391818c9237a7e35e57f861a81c32fb240589f52
