### ISSUE TITLE
Tester Server Locations get_locations__locationDbId_ metadata Incorrect

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/brapi-Java-TestServer#7]
To reproduce:

1. Visit https://app.swaggerhub.com/apis/PlantBreedingAPI/BrAPI/1.3

2. Click second GET under Locations.

3. Click "Try it out."

4. For locationDbId fill in 1.

5. Click Execute.

The result is correct but the metadata pageSize, totalCount and totalPages are all 0.  I don't know what pageSize is used by default but totalCount and totalPages should probably be 1.

**Comment by BrapiCoordinatorSelby** [comment]
Current behavior is acceptable based on the current BrAPI documentation. 

For calls which return a single object by DbId, there is no `data` array present in the response payload, and therefore there is nothing for pagination to be applied to. In this case, the `pagination` key should be ignored.

See the section on pagination for more details.
https://github.com/plantbreeding/API/blob/master/Specification/GeneralInfo/Response_Structure.md
